version: "3.9"
services:
  app:
    image: react-app:development
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: 18
    user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
