ARG NODE_VERSION=18

# we will use node docker image
FROM node:${NODE_VERSION}-alpine

# set /app as work directory
WORKDIR /app

RUN apk --no-cache add pkgconfig autoconf automake libtool nasm build-base zlib-dev

# copy your project files to work directory
COPY . .

EXPOSE 3000

CMD ["tail", "-f", "/dev/null"]
